language: cpp
compiler:
    - clang++
    - g++
script: ./travis.sh
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - g++-4.9
      - clang-3.7