language: cpp
script: ./travis.sh
os: linux
compiler:
    - clang++
    - g++
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    # if the current version of clang is lower then required try to set precisely the CXX value
    - if [[ `clang++ --version | head -n 1 | cut -c15-19` < "3.7.0" ]]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake
            - clang-3.7
            - gcc-5
            - g++-5
            