language: cpp
script: ./travis.sh
branches:
    only:
        - master
matrix:
    include:
    # works on Precise and Trusty
        - os: linux
          dist: trusty
          compiler:
                - g++
          install:
                - export CXX="g++-5" CC="gcc-5"
                - echo ${PATH}
                - echo ${CXX}
          after_success:
                # create coverage reports
                - cd ${TRAVIS_BUILD_DIR}
                - lcov --directory . --capture --output-file coverage.info # capture coverage info
                - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
                - lcov --remove coverage.info '*/test/*' --output-file coverage.info # filter out test suites
                - lcov --remove coverage.info '*/googletest/*' --output-file coverage.info # filter out googletest sources
                - lcov --list coverage.info #debug info
                # Uploading report to CodeCov
                - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - george-edison55-precise-backports
                packages:
                    - cmake-data
                    - cmake
                    - gcc-5
                    - g++-5
                    - lcov
          env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - os: linux
          dist: trusty
          compiler:
                - clang++
          install:
                # if the current version of clang is lower then required try to set precisely the CXX value
                #- if [[ `clang++ --version | head -n 1 | cut -c15-19` < "3.7.0" ]]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
                - export CXX="clang++-3.7" CC="clang-3.7"
                - echo ${PATH}
                - echo ${CXX}
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - george-edison55-precise-backports
                    - llvm-toolchain-precise-3.7
                packages:
                    - cmake-data
                    - cmake
                    - clang-3.7
          env:
            - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"