language: cpp
script: ./travis.sh
os: linux
compiler:
    - clang++
    - g++
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake
            - clang-3.7
            - gcc-5
            - g++-5
env:
    - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
            