language: cpp
compiler:
    - clang++
    - g++
script: ./travis.sh
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - g++-5
      - clang-3.7
env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"